[package]
name = "store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
models = { path = "../models", version = "0.1.0" }
deadpool-postgres = "0.10.1" 
postgres = "0.19.1" 
tokio = "1.20.1"